2023-05-09 07:45:21,028 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 3 hosts
2023-05-09 07:45:27,173 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 3 hosts
2023-05-09 10:11:51,283 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {'nautobot': <pynautobot.core.api.Api object at 0x107423520>} on 3 hosts
2023-05-09 10:12:13,697 - nornir.core.task -    ERROR -      start() - Host 'site01-sw01': task 'hello_world' failed with traceback:
Traceback (most recent call last):
  File "/Users/joshv/Library/Caches/pypoetry/virtualenvs/automationday-demos-p_dfniLv-py3.10/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/Users/joshv/Developer/automationday_demos/nornir_example.py", line 41, in hello_world
  File "/Users/joshv/Developer/automationday_demos/nornir_example.py", line 41, in hello_world
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

2023-05-09 10:12:14,492 - nornir.core.task -    ERROR -      start() - Host 'site01-rt01': task 'hello_world' failed with traceback:
Traceback (most recent call last):
  File "/Users/joshv/Library/Caches/pypoetry/virtualenvs/automationday-demos-p_dfniLv-py3.10/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/Users/joshv/Developer/automationday_demos/nornir_example.py", line 41, in hello_world
  File "/Users/joshv/Developer/automationday_demos/nornir_example.py", line 41, in hello_world
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

2023-05-09 10:12:15,097 - nornir.core.task -    ERROR -      start() - Host 'site02-rt01': task 'hello_world' failed with traceback:
Traceback (most recent call last):
  File "/Users/joshv/Library/Caches/pypoetry/virtualenvs/automationday-demos-p_dfniLv-py3.10/lib/python3.10/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/Users/joshv/Developer/automationday_demos/nornir_example.py", line 41, in hello_world
  File "/Users/joshv/Developer/automationday_demos/nornir_example.py", line 41, in hello_world
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit

2023-05-09 10:12:17,819 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {'nautobot': <pynautobot.core.api.Api object at 0x1042e7610>} on 3 hosts
